name: "conda setup"
description: "Prepare a conda environment"
inputs:
  filename:
    description: "Conda environment specification filename"
    required: false
    default: "environment.yml"
  python-version:
    description: "Conda environment Python version"
    required: false
    default: "3.9"
  env_name:
    description: "Conda environment name to create"
    required: false
    default: "xopt-dev"
  extras:
    description: "Package extras to install"
    required: true
    default: "dev"
runs:
  using: "composite"
  steps:
    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: ${{ inputs.env_name }}
        miniforge-version: latest
        use-mamba: true
        channels: conda-forge
    - name: Update Python version in environment.yml
      shell: bash -l {0}
      run: |
        if [ -f "${{ inputs.filename }}" ]; then
          sed -i -e "s/- python>=.*/- python=${{ inputs.python-version }}/" ${{ inputs.filename }}
          echo "Updated Python spec in environment file:"
          grep "python=" ${{ inputs.filename }}
        fi
    - name: Set cache date
      shell: bash -l {0}
      run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ hashFiles(inputs.filename) }}-${{ env.DATE }}
      id: cache
    - name: Update environment
      shell: bash -l {0}
      run: |
        if [ -f "${{ inputs.filename }}" ]; then
          mamba env update -n ${{ inputs.env_name }} -f ${{ inputs.filename }}
        else
          echo "No conda environment file found; skipping. Path: ${{ inputs.filename }}"
          mamba install -n ${{ inputs.env_name }} python=${{ inputs.python-version }}
        fi
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Setup the  environment
      shell: bash -l {0}
      run: |
        python -m pip install .[${{ inputs.extras }}]
