name: Examples

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
        run:
          shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          channels: conda-forge
          activate-environment: xopt-dev
          environment-file: environment.yml

      - name: Create environment
        shell: bash -l {0}
        run: |
          mamba install nbformat nbconvert ipython matplotlib

      - name: Install Xopt
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .

      - name: Run Examples
        shell: bash -l {0}
        run: |
          python scripts/run_examples.py -p "$(pwd)/docs/examples" -s
